// Custom utilities
export {
  initializeApiClient,
  initializeDefaultClient,
  getClientOptions,
  isSuccess,
  getSuccessData,
} from "./client";
import { ResultAsync } from "neverthrow";
// Generated API client exports - generated by Orval
// Uses customFetch mutator for URL redirection and header injection
export * from "./generated/client";

// Hand-written client exports for newer endpoints
export * from "./relationships";
export * from "./tags-client";
