// Custom utilities
export {
  initializeApiClient,
  initializeDefaultClient,
  getClientOptions,
  isSuccess,
  getSuccessData,
} from "./client";
export {
  ApiError,
  isApiError,
  isNetworkError,
  isRetryableError,
  unwrap,
  unwrapAsync,
  unwrapMutationFn,
} from "./errors";
export type { Unwrapped } from "./errors";
import { ResultAsync } from "neverthrow";
// Generated API client exports - generated by Orval
// Uses customFetch mutator for URL redirection and header injection
export * from "./generated/client";

// Hand-written client exports for newer endpoints
export * from "./scale";
export * from "./relationships";
export * from "./contactStrength";
